<?php

namespace AppBundle\Repository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGroupRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        return $this->createQueryBuilder('g')
            ->select('g')
            ->orderBy('g.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findbyName($research){
        return $this->createQueryBuilder('g')
            ->select('g')
            ->where('g.name = :research')
            ->setParameter('research', $research)
            ->getQuery()
            ->getResult();

    }

}
