<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */


    public function findbyName($research){
        return $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.firstName = :research or u.lastName = :research')
            ->setParameter('research', $research)
            ->getQuery()
            ->getResult();

    }
}
